#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyBodyShape.Android.Resource", IsApplication=true)]

namespace MyBodyShape.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blue_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int custom_progressbar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int down_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int front_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int help = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_3d = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_side = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int logoLong = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int next_button = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int pivotleft = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int pivotright = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int previous_button = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int results = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int rotate = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int rounded_border_edittext = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int rubis = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int signin = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int top_button = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int zoomin = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int zoomout = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070014
			public const int abdoMass = 2131165204;
			
			// aapt resource value: 0x7f07001f
			public const int avantbrasdroitMass = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int avantbrasgaucheMass = 2131165214;
			
			// aapt resource value: 0x7f070009
			public const int bodyshapeViewPager = 2131165193;
			
			// aapt resource value: 0x7f07001d
			public const int brasdroitMass = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int brasgaucheMass = 2131165212;
			
			// aapt resource value: 0x7f070017
			public const int cuissedroiteMass = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int cuissegaucheMass = 2131165206;
			
			// aapt resource value: 0x7f070022
			public const int errorInfo = 2131165218;
			
			// aapt resource value: 0x7f070015
			public const int fesseMass = 2131165205;
			
			// aapt resource value: 0x7f070008
			public const int generateButton = 2131165192;
			
			// aapt resource value: 0x7f070011
			public const int headMass = 2131165201;
			
			// aapt resource value: 0x7f070003
			public const int heightText = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int height_btn_minus = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int height_btn_plus = 2131165188;
			
			// aapt resource value: 0x7f070025
			public const int iconbodyshape = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int iconhelp = 2131165220;
			
			// aapt resource value: 0x7f070027
			public const int iconsign = 2131165223;
			
			// aapt resource value: 0x7f070019
			public const int jambedroiteMass = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int jambegaucheMass = 2131165208;
			
			// aapt resource value: 0x7f070000
			public const int layoutGenerate = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int layoutGenerateCenter = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int layoutPicture1Container = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int layoutPicture2Container = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int layoutResults = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int loadpicture1Button = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int loadpicture2Button = 2131165199;
			
			// aapt resource value: 0x7f070026
			public const int logobodyshape = 2131165222;
			
			// aapt resource value: 0x7f070021
			public const int maindroiteMass = 2131165217;
			
			// aapt resource value: 0x7f070020
			public const int maingaucheMass = 2131165216;
			
			// aapt resource value: 0x7f070012
			public const int neckMass = 2131165202;
			
			// aapt resource value: 0x7f07001b
			public const int pieddroitMass = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int piedgaucheMass = 2131165210;
			
			// aapt resource value: 0x7f07000b
			public const int takepicture1Button = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int takepicture2Button = 2131165198;
			
			// aapt resource value: 0x7f070013
			public const int thoraxMass = 2131165203;
			
			// aapt resource value: 0x7f070023
			public const int totalMass = 2131165219;
			
			// aapt resource value: 0x7f070006
			public const int weightText = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int weight_btn_minus = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int weight_btn_plus = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Generate = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Picture1 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Picture2 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Results = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int window_title = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int CustomTheme = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int CustomWindowTitleBackground = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int button_text = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int provider_paths = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
